### PR TITLE
Bootstrap 4.0.0 beta

### PR DESCRIPTION
**Pull request by jdorfman**
Need to:
- [x] Upload to CDN
- [x] Generate SRI: `run node ./scripts/integrity.js`
- [x] Replace "Alpha" link with Beta?
- [x] Decide to keep 3.3.7 on home page or go all in with 4-beta
- [x] **Make sure tests pass before merging!!!!**

RFC @XhmikosR @jmervine

### CODE REVIEW

**Comment by jdorfman** [comment]
gah, can't run `node make start`

```
 ~/github/maxcdn/bootstrap-cdn  ± (4.0.0-beta U:2 ✗)
> node ./node_modules/.bin/forever logs app.js
data:    app.js:27031 - /Users/jdorfman/github/bootstrap/bootstrap-cdn/node_modules/js-yaml/lib/js-yaml/loader.js:171
data:    app.js:27031 -   throw generateError(state, message);
data:    app.js:27031 -   ^
data:    app.js:27031 - Error
data:    app.js:27031 -     at generateError (/Users/jdorfman/github/bootstrap/bootstrap-cdn/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
data:    app.js:27031 -     at throwError (/Users/jdorfman/github/bootstrap/bootstrap-cdn/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
data:    app.js:27031 -     at readBlockMapping (/Users/jdorfman/github/bootstrap/bootstrap-cdn/node_modules/js-yaml/lib/js-yaml/loader.js:1080:7)
data:    app.js:27031 -     at composeNode (/Users/jdorfman/github/bootstrap/bootstrap-cdn/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
data:    app.js:27031 -     at readBlockSequence (/Users/jdorfman/github/bootstrap/bootstrap-cdn/node_modules/js-yaml/lib/js-yaml/loader.js:928:5)
data:    app.js:27031 -     at composeNode (/Users/jdorfman/github/bootstrap/bootstrap-cdn/node_modules/js-yaml/lib/js-yaml/loader.js:1363:45)
data:    app.js:27031 -     at readBlockMapping (/Users/jdorfman/github/bootstrap/bootstrap-cdn/node_modules/js-yaml/lib/js-yaml/loader.js:1062:11)
data:    app.js:27031 -     at composeNode (/Users/jdorfman/github/bootstrap/bootstrap-cdn/node_modules/js-yaml/lib/js-yaml/loader.js:1332:1
```

**Comment by jdorfman** [comment]
@jmervine @XhmikosR I think we follow @mdo's lead and just push `4.0.0-beta` as the default. LMK

**Comment by jdorfman** [comment]
Dealing with tomorrow, need to update jQuery and add some plugin. Too tired

cloudapp annotation 2017-08-10 at 10 32 54 pm

**Comment by XhmikosR** [comment]
I rebased the branch so that things work.

1. Now, regarding alpha -> beta. We need to setup a redirection.
2. v4 beta requires popper.js to be includes
3. We can't make the v4 latest, because Bootswatch themes and our HTML code need to be adapted

**Comment by XhmikosR** [comment]
OK, I fixed MANY things.

Travis tests still fail, so please do NOT merge until everything is green.
The errors seem to come because not all v4 files are on the CDN.

`https://maxcdn.bootstrapcdn.com/twitter-bootstrap/4.0.0-beta/js/bootstrap.min.js` returns 403
`https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js` returns 200

Now sure how to proceed. `twitter-bootstrap` is wrong, but I suppose we kept it for historical reasons and/or didn't want to set up a redirect. Now it doesn't make any sense to keep it for v4.

@jdorfman: please also add me in the AppVeyor account as admin.

**Comment by jmervine** [comment]
I copied `bootstrap-cdn/public/bootstrap/4.0.0-beta` to `bootstrap-cdn/public/twitter-bootstrap/4.0.0-beta`.

**Comment by XhmikosR** [comment]
Can't we just get rid of Twitter for v4 and on?

**Comment by XhmikosR** [comment]
Also let me know about the approach I followed

**Comment by jmervine** [comment]
👍 Looks good to me.

I'm down to drop `twitter-bootstrap` going forward, @jdorfman ? That said, I don't feel strongly one way or another, nor would I let it block moving forward.

**Comment by jdorfman** [comment]
@XhmikosR this makes no sense:

cloudapp annotation 2017-08-11 at 7 13 27 pm

Why have a link to `Beta` when it is first on the home page?

"Quick Start" needs to be simple. Show either `4.0.0-beta` or `3.3.7`. Mark seems to want to push the beta so I am leaning towards that.

**Comment by XhmikosR** [comment]
I already talked with Mark and he's fine with this.

**Comment by jdorfman** [comment]
Cool, I have an early flight tomorrow, let's talk Monday. Thanks dude

**Pull request merged**
