### PR TITLE
Use only the used Font Awesome icons.

### PR DESCRIPTION
**Pull request by XhmikosR**
Use only the used Font Awesome icons.

This saves ~80KB from the total page size.

I open this for discussion before going ahead with it.

### CODE REVIEW

**Comment by XhmikosR** [comment]
So, after #821, we only use `fa-flag` icon from Font Awesome. It's an overkill to load it just for one glyph.

Personally, I would just remove it. What do you guys think?

/CC @jmervine @jdorfman

**Comment by jmervine** [comment]
👍

**Comment by XhmikosR** [comment]
Huh? Why was this merged?

**Comment by jmervine** [comment]
Apologies, I was doing a release and miss read the comments and thought it was ready to go. Wanted to clean out the open PRs for the release.

**Pull request merged**
