### PR TITLE
Add missing solar theme

### PR DESCRIPTION
**Pull request by bostondevin**
This one somehow was missing

### CODE REVIEW

**Comment by XhmikosR** [comment]
Thanks but you need to update config.yml too.

**Comment by bostondevin** [comment]
Where are you getting the sri value from? Looks like a ssh key or something - I don't know how to generate that

**Comment by XhmikosR** [comment]
You can do it manually or use srihash.org

**Comment by bostondevin** [comment]
hmmm srihash.org wants a URL, so the file would have to exist there already

e.g.
https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/solar/bootstrap.min.css

**Comment by XhmikosR** [comment]
Right. Then use scripts/integrity.js.

**Comment by bostondevin** [comment]
not sure what u mean - this is more complicated than one would think!

**Comment by XhmikosR** [comment]
I'll have a look and add it myself later then.

**Comment by bostondevin** [comment]
that would be awesome - thanks! Never heard of sri's before

**Comment by XhmikosR** [comment]
Do you know when solar was added?

**Comment by bostondevin** [comment]
I can't quite place it. It's on their website as being in this latest version - you might have needed to build the project or something to create the new files - i dunno

**Comment by jdorfman** [comment]
Thanks @bostondevin !

**Pull request closed without merging**
