### PR TITLE
Deps

### PR DESCRIPTION
**Pull request by jmervine**
@XhmikosR Creating this PR for tracking, we'll when things are passing travis.

### CODE REVIEW

**Comment by jmervine** [comment]
Nice work btw, I'd been wanting to switch to pug.

**Comment by XhmikosR** [comment]
Only issue I see so far, is that we get this in the HTML

```html
<script>:uglify-js
```

**Comment by XhmikosR** [comment]
If you can't figure it out, we could remove of uglifying inline JS.

**Comment by jmervine** [comment]
Oh. Nice catch. I'll check it out in the am.

**Comment by XhmikosR** [comment]
@jmervine: can I rebase this branch and force push? You'll need to do `git fetch && git reset --hard` while on the local deps branch. Just don't have any local uncommitted/unpushed stuff.

**Comment by jmervine** [comment]
Yeah, @XhmikosR feel free, thanks for the heads up. Looks like I am going to sleep about the time you get up.

**Comment by XhmikosR** [comment]
I will split the pugjs change to a separate branch. I see 2 issues so far, one is the uglify filter and two, the HTML is not minified anymore.

**Comment by XhmikosR** [comment]
@jmervine: please check and merge.

**Comment by jmervine** [comment]
@XhmikosR snky was passing on this before, odd.

**Comment by jmervine** [comment]
@XhmikosR the pug changes dropped off this branch, was that intentional?

**Comment by jmervine** [comment]
I see you split them to a new PR, good call... merging.

**Comment by XhmikosR** [comment]
Yeah that is why CI was green.

**Pull request merged**
