### PR TITLE
Add AppVeyor

### PR DESCRIPTION
**Pull request by XhmikosR**
Since, I'm a Windows user and recently snyk messed up everything, I'd like to have AppVeyor for Windows CI.

Also, it shouldn't hurt having 2 CIs running.

/CC @jdorfman @jmervine

### CODE REVIEW

**Comment by XhmikosR** [comment]
It seems for some reason, on Windows we get 1848 tests vs 3161 on Travis.

**Comment by XhmikosR** [comment]
Also, note that AppVeyor would still pass with snyk because they have MSYS in PATH, so in turn `patch` in PATH. Wrong but it's for convenience.

**Comment by jdorfman** [comment]
If this helps interoperability between developer environments then I am all for it.

@jmervine thoughts?

**Comment by jmervine** [comment]
I haven't had a chance to look at AppVeyor, but I agree with @jdorfman, that if it helps cross platform, +1.

**Comment by XhmikosR** [comment]
But how about Snyk?

**Comment by jmervine** [comment]
How about we leave Snyk in, but move it to it's own task and have it not run w/ `npm test`. That way we can run it optionally.

**Comment by XhmikosR** [comment]
And prepublish seems to run on npm install.

**Comment by jmervine** [comment]
Yeah, then just kill the `republish` entry as well. We'll have to manually run `snyk` and `snyk-protect` when we need/want it.

**Pull request merged**
