### PR TITLE
adding canonical and removing referrer

### PR DESCRIPTION
**Pull request by jmervine**
RE #641 cc: @jdorfman @XhmikosR

### CODE REVIEW

**Comment by XhmikosR** [comment]
I can't check this thoroughly but the concept seems goods to me. As long as
the variables are properly set that is.

On a side note we should also look into adding social tags later.

**Comment by jmervine** [comment]
@XhmikosR You can see the result here: https://bootstrapcdn-dev-pr-672.herokuapp.com/

For example https://bootstrapcdn-dev-pr-672.herokuapp.com/bootlint/ has:

```
<link rel="canonical" href="http://bootstrapcdn-dev-pr-672.herokuapp.com/bootlint/">
```

**Comment by XhmikosR** [comment]
Why not https?

**Comment by jmervine** [comment]
@XhmikosR That's actually a good question, it should be. Perhaps the Protocol isn't being passed on correctly through Heroku's routing layer? I'll need to investigate.

**Comment by jmervine** [comment]
I think I found the answer here, testing it now... http://stackoverflow.com/a/16405622/832409

**Comment by XhmikosR** [comment]
@jdorfman please look into adding me to BootstraCDN. We can always chat
with Justin via Hangouts.

**Comment by jmervine** [comment]
I still want to dig in to why this is occurring, but for now, I'm hard coding it to `https` as we force `https` in production anyway.

**Comment by jmervine** [comment]
Better...
```
<link rel="canonical" href="https://bootstrapcdn-dev-pr-672.herokuapp.com/bootlint/">
```

**Comment by XhmikosR** [comment]
It's I need strange since the protocol is https.

Might be better investigating this  before merging.

**Comment by jmervine** [comment]
Fair. I'll have to table it then. I'm fairly certain it's something behind the scenes with the Heroku deploy. It shouldn't be too hard to figure out.

**Comment by jmervine** [comment]
Yeah, so [that](https://github.com/MaxCDN/bootstrap-cdn/pull/672/commits/713bc46a307a1fdc22c9a43f8008f855a82f61ff) seems to have done the trick. Looks like Express isn't setting the header correctly on forward. Based on what I'm reading `enable('trust proxy')` should have worked.

**Comment by jdorfman** [comment]
🚢 'd

**Pull request merged**
