### PR TITLE
Add Bootstrap v4.0.0-beta.3.

### PR DESCRIPTION
**Pull request by XhmikosR**
**Do not merge yet!!**

After Mark tags beta3 then we need to:

- [x] update the files again
- [x] upload them to the CDN
- [x] run `npm run integrity`
- [x] make sure tests are green

### CODE REVIEW

**Comment by jdorfman** [comment]
@XhmikosR uploaded

**Comment by jdorfman** [comment]
@XhmikosR the files should go into `bootstrap` not `twitter-bootstrap` that is where the CDN pull from.

**Comment by XhmikosR** [comment]
There's no bootstrap folder in public @jdorfman

**Comment by jdorfman** [comment]
@XhmikosR push this to prod asap

**Pull request merged**
