### PR TITLE
Move jQuery code in jquery-pack.js.

### PR DESCRIPTION
**Pull request by XhmikosR**
This way, we can async load the vanilla JavaScript code.

/CC @jmervine

### CODE REVIEW

**Comment by jdorfman** [comment]
I want to discuss this first

**Comment by XhmikosR** [comment]
What exactly you want to discuss?

**Comment by XhmikosR** [comment]
@jdorfman: ping or we should merge this since it doesn't have any downside, only improvement.

**Comment by jmervine** [comment]
I would prefer to load jquery off a cdn, is there a way we can load this off https://code.jquery.com/ instead of including it in our repo?

**Comment by XhmikosR** [comment]
This isn't jQuery. I simply split our JS code.

**Comment by jmervine** [comment]
😊 I see, my bad. Okay then, 👍 if @jdorfman is good with it.

**Comment by XhmikosR** [comment]
@jdorfman: ping

**Comment by XhmikosR** [comment]
I'm gonna merge this since I need it for my other changes.

**Pull request merged**
