### PR TITLE
removing etag and adjusting cache-control headers

### LINKED ISSUE #699: Remove ETags
```js
app.set('etag', false);
```

The CDN files themselves have this header too.

### LINKED ISSUE #708: Revisit cache control header
For HTML we shouldn't have `2592000` s = 30 days. Maybe `3600` (1 hour) tops.

Now, for the static assets, CSS, images, JS, we **should** use a long time. But in order to prevent issues, we should add cache busting.

### PR DESCRIPTION
**Pull request by jmervine**
Fixes #708, fixes #699 

Had to reorder mw a little to ensure that things were applied in the proper order. Additionally, I removed the `Expires` header, as without `ETag`, it shouldn't be necessary any more.

### CODE REVIEW

**Comment by XhmikosR** [comment]
It seems the static files still have ETag set.

**Comment by XhmikosR** [comment]
Also, I do believe we should set `Expires` too along with `Last-Modified` (`lastModified` expressjs option) for HTML.

**Comment by XhmikosR** [comment]
I added a couple more patches @jmervine. Ideally I guess I should make a new PR, but you know :p

**Comment by XhmikosR** [comment]
So from my suggestions above, only `Last-Modified` is left for HTML to add.

**Comment by XhmikosR** [comment]
I wonder if we could just use https://github.com/h5bp/server-configs-node.

**Comment by jmervine** [comment]
I left the Etag on the static assets because they're not served through the cdn. Not while we're using s3.

**Comment by jmervine** [comment]
These all look good. I think Travis is failing because of bootlint minify changes. Merge that and rebase and it should be good.

**Pull request merged**
