### PR TITLE
Require node.js >= 4.0.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by jmervine** [comment]
The issue with this is I wanted to match the node version that it will be running on in Heroku. I'm not oppose to this change, but can we also include `5` when running on Travis.

**Comment by XhmikosR** [comment]
So Heroku runs 5? Can we make it use 4?

**Comment by jmervine** [comment]
Probably, I'll look it.

**Comment by jmervine** [comment]
Yes, here... https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

I can make the update, do you have a specific version of 4.x you want to use?

**Comment by XhmikosR** [comment]
I'd say the latest LTS, 4.4.7 at the moment. Can't this process be automated to keep using the latest LTS at the time?

**Comment by jmervine** [comment]
From that doc...

> You can also specify a semver range (4.x). This is not recommended in production, where runtime versions should not float.

**Comment by jmervine** [comment]
That said, I'm cool with using `4.x`. We'd have to update when the next LTS major version is bumped.

**Comment by XhmikosR** [comment]
I think that is the whole idea of LTS.

**Comment by jmervine** [comment]
@XhmikosR made the change

**Comment by jmervine** [comment]
worked 

```
jmervine@laptop:~$ heroku run -a bootstrapcdn-dev node --version
Running node --version on ⬢ bootstrapcdn-dev... up, run.8560
v4.4.7
```

**Pull request merged**
