### PR TITLE
Integration page update

### PR DESCRIPTION
**Pull request by jdorfman**
Added freeCodeCamp to the integration page.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Please do not modify package lock.

**Comment by XhmikosR** [comment]
And the rest don't merge. I have it many similar changes in my bootstrap 4
branch. No need for this to go in before that.

**Comment by jdorfman** [comment]
@XhmikosR should I add `package-lock.json` to`gitignore`?

**Comment by XhmikosR** [comment]
No. It's a bug in npm like I told you the other day.

Please do not merge. For one you should have squashed tour patches. Second
the package file. Third I'm pretty sure I will achieve better image
compression. Fourth it will conflict with my bootstrap 4 branch where I
changed to use an alert. Generally this should be closed and we can add the
new entry after my PR is merged.

**Comment by jdorfman** [comment]
k when you're done, merge this branch.

**Pull request closed without merging**
