### PR TITLE
Move footer outside of the main content.

### PR DESCRIPTION
**Pull request by XhmikosR**
* Move ads to the left of the main content, keep Twitter timeline to the right
* Move footer outside of the main content

This is a first idea. I've always been meaning to move footer outside of content.

Let me know if you have any suggestions to improve this.

### CODE REVIEW

**Comment by jmervine** [comment]
I'm happy with the footer, but personally, prefer the ads where they were. I feel like this squeezes the center column too much on smaller displays.

**Comment by XhmikosR** [comment]
How small you mean? Because currently I have it use the full row up until md breakpoint.

**Comment by jmervine** [comment]
Here's what I'm looking. Browser width is currently 1650px.

screen shot 2017-12-12 at 9 19 01 am

**Comment by jmervine** [comment]
Perhaps removing padding from the left and right might help?

**Comment by XhmikosR** [comment]
Well, that is normal... Because the biggest breakpoint in >= 1200px, and I use 2 + 5 + 2 columns, otherwise on very big resolutions the content is full width. There's no padding, just flexbox.

**Comment by jmervine** [comment]
Fair. I still prefer the ads where they were, on the right. But I don't feel super strongly about it.

I'll leave it to @jdorfman to decide.

**Comment by XhmikosR** [comment]
Have one more look, I made everything use a little more space.

**Comment by jmervine** [comment]
It looks better, for sure. I still prefer it the way it was, on the right, but I'll defer to @jdorfman.

**Comment by XhmikosR** [comment]
All right, let me know, and I can revert the ads move and just keep the footer change.

**Comment by XhmikosR** [comment]
So, I reverted the ads move. I think I can merge now.

**Comment by jdorfman** [comment]
@XhmikosR the deploy link is dead

**Comment by XhmikosR** [comment]
@jdorfman: not related to this, something in the integration must fail. @jmervine: ideas?

**Pull request merged**
