### PR TITLE
Add Bootstrap 4.0.0-beta.2.

### PR DESCRIPTION
**Pull request by XhmikosR**
- [x] Update to the final beta2 release files
- [x] Verify SRI hashes
- [x] Make sure .map files and the new bundle files are on the CDN

@jdorfman @jmervine: please do NOT merge; I'll do it when it's ready. I open this to discuss the changes.

### CODE REVIEW

**Comment by XhmikosR** [comment]
So, what should we do with the new bundle file? Also note that while we have reboot and grid only files on the CDN, we don't expose them currently. Not sure if we should.

/CC @mdo for thoughts too.

**Comment by XhmikosR** [comment]
ping @jmervine @jdorfman: please add beta2 to `twitter-bootstrap` path too. That's why I had made #867...

**Comment by jdorfman** [comment]
@XhmikosR restarting build

@jmervine can we just adjust the tests to ignore `https://maxcdn.bootstrapcdn.com/twitter-bootstrap/*` starting at `4.0.0-beta.*` please?

**Comment by jdorfman** [comment]
@XhmikosR when was `twitter-bootstrap` uri changed to just `bootstrap`? We can stop checking versions after that, will speed up tests.

**Comment by jdorfman** [comment]
@XhmikosR merge when ready

**Comment by XhmikosR** [comment]
There's no point in skipping tests. You might as well remove the tests then...

The point is we need to remove `twitter` from the path somehow. Not sure when this started to break, probably in v4.

**Pull request merged**
