### PR TITLE
Updated CDN link from maxcdn.com to stackpath

### PR DESCRIPTION
**Pull request by jdorfman**

### CODE REVIEW

**Comment by XhmikosR** [comment]
Are you sure about the removal of the trailing spaces ?  IIRC they really
needed.

**Comment by jdorfman** [comment]
@XhmikosR nope that was a mistake. Reason for this
image

**Comment by XhmikosR** [comment]
Don't we have an editor config file? I thought I had set it up properly.

**Comment by jdorfman** [comment]
@XhmikosR not sure

**Comment by XhmikosR** [comment]
.editoconfig is properly set up BTW.

@jdorfman: can I rebase the branch or will you do it?

**Comment by jdorfman** [comment]
@XhmikosR you can rebase

**Comment by jmervine** [comment]
👍

**Comment by jdorfman** [comment]
@jmervine good to go. There will be more trivial updates coming but this branch can be deleted. Thanks

**Comment by XhmikosR** [comment]
Should I rebase and merge then?

**Comment by jdorfman** [comment]
@XhmikosR that would be awesome. I always F it up

**Comment by XhmikosR** [comment]
Will do as soon as I'm back home.

**Comment by XhmikosR** [comment]
@jdorfman @jmervine: are you sure about the default theme change?

**Comment by jdorfman** [comment]
@XhmikosR yes, StackPath wants it close to their colors

**Comment by XhmikosR** [comment]
Should we also change the logo and favicons?

**Comment by jdorfman** [comment]
@XhmikosR not yet but good call. I am waiting for the SVG to replace the `M`

**Comment by XhmikosR** [comment]
Should I ask my guy who made the `B` icon? I just need clear instructions.

/CC @dupstudio

**Comment by jdorfman** [comment]
Sure make it `#00afec`

**Comment by XhmikosR** [comment]
Allright, I'll bug him tomorrow evening, unless he sees the notification sooner.

**Pull request merged**
