### PR TITLE
Stop loading Twitter and GitHub buttons `onload`.

### PR DESCRIPTION
**Pull request by XhmikosR**
It seems it's actually slowing us down.

Testing this for now.

### CODE REVIEW

**Comment by jdorfman** [comment]
seems slower than before ¯\_(ツ)_/¯

**Comment by jmervine** [comment]
You can't compare a PR App to production. They auto-idle after 5 minutes, and have to wake up on first hit. As such they'll always be a bit of added latency when you first hit it. Additionally, the "hardware" there has a fraction of what's on production. If you want a side by side you need to cut a branch that's identical to develop and create a PR for that. Hit them both once to ensure they're not idling and then run a web page speed test on them.

**Comment by XhmikosR** [comment]
It seems a middle solution is to load the third-party script on `DOMContentLoaded`.

**Comment by jdorfman** [comment]
lgtm. New rule if you open it and get approval you merge it.

**Pull request merged**
