### PR TITLE
Switch to node.js 8.x.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
@jmervine: this results in Error 500. Do we need to change something else too?

**Comment by jmervine** [comment]
There shouldn't be anything else, at least not that I'm aware of. There might be something that isn't compatible with Node 8, what's the stack trace?

**Comment by jmervine** [comment]
I don't have time to troubleshoot right now, but running locally...

```
root@95ebc0d568f1:/app/user# npm test
npm info it worked if it ends with ok
npm info using npm@5.0.3
npm info using node@v8.1.4
npm info lifecycle bootstrapcdn@0.0.1~pretest: bootstrapcdn@0.0.1
npm info lifecycle bootstrapcdn@0.0.1~test: bootstrapcdn@0.0.1

> bootstrapcdn@0.0.1 test /app/user
> node make test

module.js:487
    throw err;
    ^

Error: Cannot find module 'graceful-readlink'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/user/node_modules/mocha/node_modules/commander/index.js:7:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
root@95ebc0d568f1:/app/user# node --version
v8.1.4
```

**Comment by XhmikosR** [comment]
Weird, because I run it locally just fine :/ If it errored out I wouldn't make the PR :P

**Comment by XhmikosR** [comment]
Maybe it caches somewhere the `node_modules` folder? If so it needs to be pruned.

**Comment by XhmikosR** [comment]
All seems to be good now @jmervine.

**Pull request merged**
