### PR TITLE
Replace MaxCDN icon and link

### LINKED ISSUE #820: Replace MaxCDN icon and link
We need to replace the MaxCDN "M" with the StackPath icon: https://cl.ly/471q371k282N and the URL to: https://www.stackpath.com/

image

Future updates will be replacing all MaxCDN branding/links. Thanks!

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #820.

@jdorfman: do not merge this, just look at it and let me know.

1. I used 45x45 as dimensions to match the previous icon's dimensions. Not sure if this is what you wanted.
2. I didn't use `target="_blank"`; let me know if you want to.

### CODE REVIEW

**Comment by jdorfman** [comment]
@XhmikosR checking

**Comment by jdorfman** [comment]
@XhmikosR 

> I used 45x45 as dimensions to match the previous icon's dimensions. Not sure if this is what you wanted.

Perfect

> I didn't use target="_blank"; let me know if you want to.

Your call. Not sure what the norm is these days. I usually go with `_blank` but then again I'm old school.

**Comment by XhmikosR** [comment]
Well, there's generally an issue with `target="_blank"`.  https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

But this applies to all our links so I'll have a look at a later time.

**Comment by jdorfman** [comment]
noted. Can I merge?

**Comment by jdorfman** [comment]
@jmervine can you deploy this to master please

**Pull request merged**
