### PR TITLE
Adding SRI integrity to all fields.

### PR DESCRIPTION
**Pull request by jmervine**
@jdorfman 

* Adding script to create integrity for any missing files in `config/_config.yml`.
    * This is now dynamically generated, as such, all comments, sorting and general formatting is now out the window.
* Adding integrity to all fields.
* Refactoring views and helpers to accommodate integrity.
*  Fixing `tryIt` pathing.

This is a fairly drastic change, as such, before merging I've deployed this branch here http://bootstrapcdn.herokuapp.com/.

### CODE REVIEW

**Comment by jdorfman** [comment]
@jmervine if I merge this, it will only deploy to `dev.bootstrap` not `www.bootstrap` correct?

**Comment by jmervine** [comment]
That's correct. But don't merge unless you actually want to release this, I released to a seperate location so we could review and discuss before moving forward.

**Comment by jdorfman** [comment]
@jmervine can this be closed?

**Comment by jmervine** [comment]
I'd like to merge it. Waiting for you to +1 it, it's such a major change.

**Comment by jdorfman** [comment]
sorry +1

**Comment by jmervine** [comment]
Cool. I'll try to merge and release this later this afternoon.

**Pull request merged**
