### PR TITLE
putting nav links in active mode when page is loaded

### PR DESCRIPTION
**Pull request by jmervine**
@jdorfman per your email

### CODE REVIEW

**Comment by jdorfman** [comment]
:+1: :ship:

**Comment by XhmikosR** [comment]
What is the reasoning for this?

**Comment by jmervine** [comment]
The nav button for the current page wasn't shown as active when the page was loaded. This makes it so.

**Comment by XhmikosR** [comment]
We should make use of the active class then via pug.

**Comment by jmervine** [comment]
I considered that when breaking things out in to their own pages, but it was actually more work/code to pass active through as a local in the route. That said, I have no strong preference one way or another.

**Pull request merged**
