### PR TITLE
Tweak ads style.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
Maybe I should limit the text so that it's consistent with the image size? Something like `max-width: 400px;`?

**Comment by XhmikosR** [comment]
I added a max-width so that the text has aprox. the same size as the image.

**Comment by jdorfman** [comment]
@XhmikosR thank you for reminding me. We actually would like to move it to the top right i.e. above "Mad Love". Last month we raised ~$230 for the Open Source collective. We would like to see how it will perform above the fold. Easy?

**Comment by XhmikosR** [comment]
Hmm, I'll have a go at it and let you know.

**Comment by XhmikosR** [comment]
Admittedly, the current position is just too low in the page.

**Pull request merged**
