### PR TITLE
Adding in basic support for SRI - relates to: #555

### PR DESCRIPTION
**Pull request by jonathanKingston**
@jdorfman please review, it is likely very rough / broken (done in a hurry).

Automation is the next step, this is a different conversation however :smile: 

Thanks!

### CODE REVIEW

**Comment by jdorfman** [comment]
Hey @jonathanKingston this is a perfect first step (not automated)

Looks like the JS is breaking:

`Uncaught ReferenceError: toggleCode is not defined` 
`onclick @ (index):77`

**Comment by jonathanKingston** [comment]
Yup that relates to my comment here: https://github.com/MaxCDN/bootstrap-cdn/issues/555#issuecomment-124295510

I'm not sure where that code has gone as it isn't part of my change.

**Comment by jmervine** [comment]
I'll take a look at the `toggleCode` error this weekend, that's weird.

Also, I'll probably take a stab at automating it before merging to master. I can do the research myself, but @jonathanKingston if you could include when you did to generate the `sha`s, it would save me a few minutes.

Cheers,
J

**Comment by jmervine** [comment]
@jonathanKingston (cc @jdorfman)

That error is probably due to the changes on https://github.com/MaxCDN/bootstrap-cdn/pull/553, if you rebase your branch with `develop`...

```bash
$ git remote add upstream https://github.com/MaxCDN/bootstrap-cdn.git
$ git fetch upstream
$ git rebase upstream/develop
```

There were some pretty drastic changes, but looking at your PR, there shouldn't be an conflicts.

**Comment by jdorfman** [comment]
@jmervine rebased, same error

**Comment by jonathanKingston** [comment]
Yup I think an extra few lines need adding back in that were taken out in
the latest commit in dev... I will patch.

I added a pull request to npm-sri-toolbox for the CLI I used.

Where will the file integrity be generated from, github?

**Comment by jmervine** [comment]
Odd b/c this isn't occuring on dev.bootstrapcdn.com (at least on chrome).

**Comment by jmervine** [comment]
Okay, pretty sure I found the issue, gonna push to develop once done testing and you'll need to rebase again.

Also, wondering if we should just include this by default on all example code, if it's best practice.

**Comment by jonathanKingston** [comment]
@jmervine we should certainly, I pushed this code in very late last night so I just did the first for illustration.

So yeah automation of the integrity generation would be better.


The code I was seeing missing from the main template was:
```
    <script src="https://www.hellobar.com/hellobar.js"></script>
    <script>function tabAction(t){var a=$(t).attr("href");document.location.href="/"+(document.location.search?document.location.search:"")+a+hashSuffix,hash=a}function tryIt(t){window.location.href="/?theme="+t+(hash?hash+hashSuffix:"")}function toggleCode(t,a){$("#"+a).toggleClass("hidden"),$(t).find("i").toggleClass("fa-caret-down"),$(t).find("i").toggleClass("fa-caret-up")}new HelloBar(34009,110807),$("input:text").focus(function(){$(this).select(),$(this).mouseup(function(t){t.preventDefault()})});var hash,hashURLNext=document.location.href.split("#")[1],hashSuffix="_tab";hashURLNext&&(hash="#"+hashURLNext.replace(hashSuffix,"")),hash&&$("ul.nav.navbar-nav li 
...
```

**Comment by jonathanKingston** [comment]
@jmervine the commit for the hash generation is here: https://github.com/jonathanKingston/npm-sri-toolbox/commit/79d4a082bbe0adf3705a2ab19a1b456437f0972e

So either using sri toolbox, using the command line like that or perhaps just normal open ssl:
```
cat FILENAME.js |
openssl dgst -sha256 -binary |
openssl enc -base64 -A
```

I would advocate the cli interface personally or the toolbox via scripted.

**Comment by jmervine** [comment]
Okay, I'm breaking my own rules and pushing directly to `develop`, but I pushed two quick fix commits, this is the one that fixes the `toggleCode` issue at hand...

https://github.com/MaxCDN/bootstrap-cdn/commit/bcc1fceba8613fdc7d7299aa7de4cfa4886cdc5c

J

**Comment by jonathanKingston** [comment]
Yup seems to work thanks @jmervine - celebratory beer time

**Comment by jmervine** [comment]
I'd like to release #558 to production before merging this to production. I was considering that we should implement this for everything and automatically before releasing it. But if it's a priority (that's your call @jdorfman) then we can push this out now and I'll work on getting automation in over the next week or so.

If we're going to implement it for all code, then I'll just create a script that generates the sha and includes it for all referenced files.

J

**Comment by jdorfman** [comment]
@jmervine #558 is now merged.

Let's do:
>"push this out now and I'll work on getting automation in over the next week or so."

**Comment by jonathanKingston** [comment]
:+1: thanks. Let me know if you have any issues.

**Comment by jdorfman** [comment]
Sweet. @jonathankingston I'll email you back tomorrow.

**Pull request merged**
