### PR TITLE
Adding SRI to all fields.

### PR DESCRIPTION
**Pull request by jmervine**
See #561

### CODE REVIEW

**Comment by jmervine** [comment]
@jdorfman This is available on http://dev.bootstrapcdn.com/, please review and I'll release to prod shortly.

**Comment by jonathanKingston** [comment]
:+1: @jmervine thanks for your hard work here.

**Comment by jmervine** [comment]
My pleasure! Thanks for getting the ball rolling. 😜

**Comment by jdorfman** [comment]
@jmervine I don't see the SRI fields anymore

**Comment by jonathanKingston** [comment]
@jdorfman intentional, it is now on all of them isn't it.

Can I also say this has really helped educate people about SRI:
http://stackoverflow.com/questions/32039568/what-are-the-integrity-and-crossorigin-attribute

**Comment by jdorfman** [comment]
@jonathanKingston @jmervine apologies!  I need new glasses. =p

**Pull request merged**
