### PR TITLE
Production Release

### PR DESCRIPTION
**Pull request by jmervine**
See commits

### CODE REVIEW

**Comment by jmervine** [comment]
Gonna let this sit for a bit, but it should be good to go.

**Comment by XhmikosR** [comment]
This needs a rebase against origin/develop and skipping the unneeded patches.

Also, might be worth merging #723 to develop and rebasing this afterwards.

**Comment by jdorfman** [comment]
:shipit:

**Comment by XhmikosR** [comment]
@jmervine: please fetch and rebase skipping any redundant commits before merging.

**Comment by XhmikosR** [comment]
From a quick look, you only need 2 patches, and possibly even only 1 (the first one).

**Comment by XhmikosR** [comment]
Actually, scratch my previous comment. I thought you were merging from your jmervine-default-production branch.

**Pull request merged**
