### PR TITLE
Use vanilla Twitter buttons

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
@jmervine: deployment seems to be skipped for some reason for this PR.

**Comment by jmervine** [comment]
Grrr, I'll talk to Heroku support at some point today, but I'm guessing that transferring ownership mucked things up.

I'll probably need to disable and reenable PR apps to get it working properly again.

**Comment by jmervine** [comment]
By the way, I love this, let get the PR apps working later today so we can look at it, then +1 for sure.

**Comment by XhmikosR** [comment]
Any news?

**Comment by jmervine** [comment]
@XhmikosR It looks like this one just hiccuped, the rest seemed to work fine.

**Comment by XhmikosR** [comment]
All right, so do we merge it?

**Comment by jmervine** [comment]
👍

**Pull request merged**
