### PR TITLE
Enforce LF for all files.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by jmervine** [comment]
Not sure if  the `public/font-awesome/*/.gitignore` files even need to be there. I think they came with the zip files that were used to originally create them (before my time).

**Comment by XhmikosR** [comment]
@jmervine: Hmm, do the tests run against the live files? I see Travis failing.

**Comment by jmervine** [comment]
```
  1) functional bootstrap https://maxcdn.bootstrapcdn.com/twitter-bootstrap/2.1.1/js/bootstrap.min.js has integrity:
      AssertionError: 'sha384-v2XCZ4x+SDQreGSr5HtkSOzDeIzE4K5aqWp3xcskLxq7Y5S76C4sqh/MEurBY1fz' == 'sha384-gYjuefvjBnMR9aV2JTKd0GeQnxj+mKMBirUgIH+rBsMaUe1iAC8UtOnqPrZV8s2V'
      + expected - actual
      -sha384-v2XCZ4x+SDQreGSr5HtkSOzDeIzE4K5aqWp3xcskLxq7Y5S76C4sqh/MEurBY1fz
      +sha384-gYjuefvjBnMR9aV2JTKd0GeQnxj+mKMBirUgIH+rBsMaUe1iAC8UtOnqPrZV8s2V
      
      at tests/functional_test.js:59:16
      at request (tests/functional_test.js:44:16)
      at assertSRI (tests/functional_test.js:55:5)
      at Context.<anonymous> (tests/functional_test.js:97:21)
```

**Comment by XhmikosR** [comment]
@jmervine: I'm still getting that file modified on Windows.

```shell
node sri.js C:\Users\xmr\Desktop\bootstrap-cdn\public\twitter-bootstrap\2.1.1\js\bootstrap.min.js
C:\Users\xmr\Desktop\bootstrap-cdn\public\twitter-bootstrap\2.1.1\js\bootstrap.min.js
> sha384-gYjuefvjBnMR9aV2JTKd0GeQnxj+mKMBirUgIH+rBsMaUe1iAC8UtOnqPrZV8s2V
```

It's like it was committed with CRLF.

**Comment by XhmikosR** [comment]
Also, since tests use the files on the CDN, it's normal that tests will fail, isn't it? We need to update the files after we commit/push.

**Comment by jmervine** [comment]
Typically we push to s3 before pushing the branch with new files. I can
assist in pushing to s3 in the morning, it's super later here.

**Pull request merged**
