### PR TITLE
disabling cache buster in non-prod environments

### LINKED ISSUE #741: Disable caching for development

### PR DESCRIPTION
**Pull request by jmervine**
@XhmikosR Fixes #741

### CODE REVIEW

**Comment by XhmikosR** [comment]
I don't like this solution. It's one thing disabling caching and another remove the cache busting.

**Comment by jmervine** [comment]
What's the difference?

**Comment by XhmikosR** [comment]
Because you are not disabling caching that way...

**Comment by jmervine** [comment]
I don't understand the issue here. `shift-` refresh clears the browser cache, and really cache busters shouldn't matter locally anyway, as it's not being served through the CDN.

Development needs to be a second class citizen. Minor changes, okay, but making larger changes -- e.g. headers, etc. -- for development, I don't agree with.

I'm going to close this, because as you say, it really doesn't help in any way.

**Comment by XhmikosR** [comment]
I agree. It's just at the moment, development is having issues and I'm trying to pinpoint the cause.

**Pull request closed without merging**
