### PR TITLE
Production release

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by jdorfman** [comment]
LGTM, @jmervine please review and merge =)

**Comment by XhmikosR** [comment]
Yeah, it felt unnatural going clockwise and I kept forgetting to change it :/

**Comment by XhmikosR** [comment]
@jmervine: Hmm, shouldn't you **not** squash?

Better reset master to develop and we agree on the merge type for master.

**Comment by jdorfman** [comment]
@XhmikosR check slack

**Pull request merged**
