### PR TITLE
Remove class and move it to style.css.

### PR DESCRIPTION
**Pull request by XhmikosR**
@jmervine: we need to update the SRI hash for style.css. How do you generate them? With integrity.js? Because I'm getting tons of changes in hashes locally.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Oh, also, maybe we should automate our assets SRI hash generation to save us some time in the future.

**Comment by jmervine** [comment]
@XhmikosR `scripts/integrity.js` does that for all assets (Bootstrap, etc.) and updates config.json,  it wouldn't be that hard to expand it. We should also probably add a make task for it. Adding an issue to do so.

**Comment by XhmikosR** [comment]
Weird, because I get tons of changes when I run it. Can you run it and compare the changes?

**Comment by jmervine** [comment]
In the mean time, can you run `scripts/sri.js` on this file and update the config?

**Comment by XhmikosR** [comment]
Wait for CI to finish, and check the deployment just to be safe.

I still believe we should check the hash stuff because I see a lot of differences even when I change everything to use LF.

**Comment by jmervine** [comment]
Fair, most of the SRI's are being tested, I believe, but perhaps not style.css, that said, it should change with an change to the file.

**Comment by XhmikosR** [comment]
I think we are all set.

**Pull request merged**
