### PR TITLE
Remove Glyphicons from the Resources dropdown.

### PR DESCRIPTION
**Pull request by XhmikosR**
Bootstrap 4 doesn't use it.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Well, it might be too soon, I'd give you that. But other than that, it doesn't make sense for us to keep having it since it's no longer used. I mean, what if a component was used in v2.x, would we still list it?

**Comment by jmervine** [comment]
@jdorfman your call

**Comment by jdorfman** [comment]
@XhmikosR merge when ready. WordPress should be next. If @petarpetrovic ever get around to updating it we can re-add it.

**Comment by XhmikosR** [comment]
I removed WordPress plugin too.

**Pull request merged**
