### PR TITLE
Production release

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
I want to fix a couple more things but I'm afk so please don't merge yet.
I'll fix it when I'm back in a couple of hours and push it in my other PR.

**Comment by jmervine** [comment]
I'm jumping on a plane here shortly, so I'm not merging anything. ;)

**Comment by jdorfman** [comment]
@XhmikosR after merging the logo in the top left corner broke.

image

**Comment by XhmikosR** [comment]
True. Doesn't happen in Firefox which I use. Please revert the logo
optimization commit and redeploy.

**Pull request merged**
