### PR TITLE
Convert showcase and integration images to 8-bit.

### PR DESCRIPTION
**Pull request by XhmikosR**
Before: 1,38 MB (1.452.164 bytes)
After:  624 KB (639.759 bytes)

### CODE REVIEW

**Comment by jdorfman** [comment]
Great find. So many more to add:

```
https://kubernetesbootcamp.github.io/kubernetes-bootcamp/1-2.html
https://gfycat.com/
http://governor.virginia.gov/
http://www.citysearch.com/guide/los-angeles-ca
http://www.espn975.com/
https://appcenter.intuit.com/
http://blog.williams-sonoma.com/
http://radio.com/
http://activate.mlb.com/
https://gfycat.com/
http://jr.nba.com/
http://www.smithsonianmag.com/?no-ist
http://www.iwantnflnetwork.com/
```

**Comment by XhmikosR** [comment]
Do we do this manually?

Also, might be a good idea to start looking to implement pagination, and/or search, or at least mixItUp to filter the entries.

**Comment by jdorfman** [comment]
Yeah, it is manual. I think AI for this would be overkill.

> start looking to implement pagination, and/or search, or at least mixItUp to filter the entries.

Possibly. Those pages don't get a lot of traffic:

image

**Comment by XhmikosR** [comment]
I was under the impression people needed to contact us to add their entries, that's why I ask.

Feel free to make an issue to track this and add more entries if you want.

**Comment by jdorfman** [comment]
Nah I just `view source` anytime I see Font Awesome or Bootstrap being used. 

Oh nice! I will do that. =)

**Pull request merged**
