### PR TITLE
test s3 for everything w/ TEST_S3

### PR DESCRIPTION
**Pull request by jmervine**
note this branch is poorly named :P

### CODE REVIEW

**Comment by jdorfman** [comment]
:ship:

**Comment by jmervine** [comment]
I'll merge in a bit, waiting for one final file to get perged and then I'm going to push a change the turns on `TEST_STRICT` by default, now that everything should be conforming to the strict content type.

**Comment by jdorfman** [comment]
@jmervine did support purge the file(s)

**Comment by jmervine** [comment]
@jdorfman Yes, everything got crazy today. I'll look at this later tonight or tomorrow morning.

**Comment by jdorfman** [comment]
needs a yaml file

**Pull request closed without merging**
