### PR TITLE
Switch to helmet.js for the security related headers.

### LINKED ISSUE #743: Set `X-Frame-Options`, `X-XSS-Protection` for HTML files only
Also, cache HTML files only with max-age=3600. I noticed that currently we set those headers for xml files too, like sitemap.xml.

### LINKED ISSUE #773: Add helmet
https://github.com/helmetjs/helmet

Instead of us doing this manually, we could use helmet.

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #773, fixes #743

### CODE REVIEW

**Comment by XhmikosR** [comment]
@jmervine: Heroku throws an error here when I try to visit https://bootstrapcdn-dev-pr-777.herokuapp.com/

**Comment by jmervine** [comment]
I'm guessing the app expired. I know they have a limited lifetime to keep costs down.

**Comment by jmervine** [comment]
Redeployed and working.

**Comment by XhmikosR** [comment]
This isn't ready to be merged yet due to HSTS not being added. I'll keep an eye on helmetjs.

**Comment by XhmikosR** [comment]
@jmervine: can you redeploy this branch?

**Pull request merged**
