### PR TITLE
Update Bootswatch to v3.3.7.

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @jmervine to upload the files on the CDN

### CODE REVIEW

**Comment by jdorfman** [comment]
Uploaded + Purged

- https://maxcdn.bootstrapcdn.com/bootswatch/latest/cerulean/bootstrap.min.css
- https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cerulean/bootstrap.min.css

**Comment by XhmikosR** [comment]
@jmervine is it possible to keep the deployments showing up in  the PR for
a little longer?

**Comment by jmervine** [comment]
No, as soon as it's merged, the pr app is deleted.

**Comment by XhmikosR** [comment]
All right, how about having SSL for dev too? Just trying to mimic the
production environment as close as possible.

**Comment by jmervine** [comment]
Hmm, I think Heroku now has a free ssl service, if not GA, at least in beta. I'll look in to it.

**Pull request merged**
