### PR TITLE
Production Release

### PR DESCRIPTION
**Pull request by jmervine**
@XhmikosR @jdorfman 

There's been a lot of updates since the last release, time to do another. Verify that dev.bootstrapcdn.com looks good and I'll merge.

Cheers!

### CODE REVIEW

**Comment by XhmikosR** [comment]
LGTM

**Comment by jdorfman** [comment]
Checking

**Comment by jdorfman** [comment]
@XhmikosR is it possible to have the same padding lengths between the social buttons?

**Comment by XhmikosR** [comment]
I'm thinking that we should get rid of that last iframe at this point. But that's for another day.

To answer your question, it should be possible, yes.

**Comment by XhmikosR** [comment]
Any idea why the main site didn't get updated after the merge? Does the
deployment only work if Joshua makes the merge?

**Comment by jmervine** [comment]
It didn't release because CI didn't pass.

**Comment by jmervine** [comment]
Wait actually they did, if you look at the [merge commit here](https://github.com/MaxCDN/bootstrap-cdn/commits/master). I'm going to have to look at it and see why. It should have.

**Comment by jmervine** [comment]
This is probably the cause...

screen shot 2016-09-02 at 12 55 47 pm

**Comment by jmervine** [comment]
Manually deploying...

**Comment by jmervine** [comment]
It's now live.

**Pull request merged**
