### PR TITLE
extras_popular.jade: Add jQuery Tablesorter plugin.

### PR DESCRIPTION
**Pull request by XhmikosR**
This allows us to sort the table.

TODO:
- [x] Get rid of the empty `th` or disable sorting for the empty columns
- [x] Figure out the reason sorting is weird for the counts
- [x] check out the themes

@jmervine; don't merge this yet until I fix the TODO, but feel free to try it in action too :)

### CODE REVIEW

**Comment by XhmikosR** [comment]
@jmervine: can you try this? I tried to keep it as close as possible to the current style.

**Comment by jmervine** [comment]
Crazy busy this week with my day job, but I'll take a look for sure.

**Comment by jmervine** [comment]
@XhmikosR Oh, that's pretty! Nice work! I'm  moving it to dev (http://dev.bootstrapcdn.com/) now. Take a look and let me know what you think.

**Comment by XhmikosR** [comment]
@jmervine: I think it works pretty good. Only thing I wanted to change is the order of stylesheets. But I was too lazy so I simply made a few changes in the theme CSS. I might get to do this properly in the future to make updates easier.

**Comment by XhmikosR** [comment]
@jmervine: what happened to this? I don't see it in the master? How exactly did you merge from develop? Not sure if other stuff are missing too.

**Comment by jmervine** [comment]
@XhmikosR I'll get this merged shortly. I haven't merged develop in to master since we had a few production issues a couple of weeks ago. The last few changes were via specific cherry-picks to make critical updates. I'm going to spend some time getting master and develop back in sync by the end of this coming weekend. I was at Scale Thur-Sun so didn't have a chance this past weekend.

J

**Comment by jmervine** [comment]
@XhmikosR Okay, everything's cleaned up and `develop` and `master` are back in sync, both released to their respective hosts. Apologies for the delay.

**Comment by XhmikosR** [comment]
Cool, thanks!

PS. tests are failing and we need to update deps too.

**Comment by jmervine** [comment]
Yeah, it's on my list. :-/

**Pull request merged**
