### PR TITLE
Update social.pug

### PR DESCRIPTION
**Pull request by XhmikosR**
This is WIP since I changed the URL to `https`. I also changed the `via` account to `getbootstrapcdn` and added `jdorfman` to the related parameter.

### CODE REVIEW

**Comment by XhmikosR** [comment]
I need @jdorfman thoughts too since this will probably break the old Twitter analytics.

**Comment by jmervine** [comment]
@jdorfman I'll wait for your +1 before merging.

**Comment by XhmikosR** [comment]
Ping @jdorfman

**Comment by jmervine** [comment]
@jdorfman ping

**Comment by jdorfman** [comment]
Make it happen captain. Sorry for the delay.

**Pull request merged**
