### PR TITLE
Add Bootswatch Solar theme.

### PR DESCRIPTION
**Pull request by XhmikosR**
Closes #848

### CODE REVIEW

**Comment by XhmikosR** [comment]
@jmervine @jdorfman: do we need to add the new files manually to the CDN? Or is it enough if I merge this and then merge to master?

**Comment by jdorfman** [comment]
@XhmikosR need to upload it

**Comment by jdorfman** [comment]
merge, it's uploaded

**Comment by XhmikosR** [comment]
@jdorfman: it's already merged :P

I pinged @jmervine on slack the yesterday.

**Pull request merged**
