### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
Travis fails since Bootlint checks for Bootstrap version which we use from Bootswatch.

**Comment by XhmikosR** [comment]
CC @thomaspark for pingback when you update Bootswatch for 3.3.2.

**Comment by jmervine** [comment]
I'd like to see this pass on travis before merging, I initiated a new build manually and will check back in a bit.

**Comment by XhmikosR** [comment]
It won't change anything until Bootswatch is updated for 3.3.2...

**Comment by thomaspark** [comment]
Just updated Bootswatch to 3.3.2 in the official repo. Let me know if you want me to do it here.

**Comment by XhmikosR** [comment]
@thomaspark: thanks! But in order for this to work we need Bootswatch 3.3.2 added here too.

**Comment by thomaspark** [comment]
Opened pull request at lucky #500.

**Comment by XhmikosR** [comment]
Thanks, I'm gonna wait until that is merged and then rebase this one.

**Comment by XhmikosR** [comment]
Rebased @jmervine

**Pull request merged**
