### PR TITLE
4.0.0-beta

### PR DESCRIPTION
**Pull request by jdorfman**

### CODE REVIEW

**Comment by XhmikosR** [comment]
err, sec, something isn't right.

**Comment by jdorfman** [comment]
@XhmikosR just look at it tomorrow, no rush

**Comment by XhmikosR** [comment]
>This branch is out-of-date with the base branch
Merge the latest changes from master into this branch. 

This shouldn't happen.

**Comment by jdorfman** [comment]
That's what I thought. But again, worry about it later

**Comment by XhmikosR** [comment]
All right, I'll have a look when I'm back.

**Comment by XhmikosR** [comment]
Now that I think about it just merge it and I'll reset the master branch if
you remove the protection when I'm back.

**Comment by XhmikosR** [comment]
@jdorfman: the master is still protected.

**Comment by jmervine** [comment]
Nice work!

**Comment by jdorfman** [comment]
@XhmikosR meaning?

**Comment by XhmikosR** [comment]
I can't force push it.

**Pull request merged**
