### PR TITLE
un-asyncing exec, simplifying exec calls

### PR DESCRIPTION
**Pull request by jmervine**
Addressing errors running `node make travis` and other serialized tasks.

@XhmikosR

### CODE REVIEW

**Comment by jmervine** [comment]
@XhmikosR Let me know when you've had a chance to test this again locally.

**Comment by XhmikosR** [comment]
@jmervine: works as fast as before now, but I'm getting failures.


```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\xmr\Desktop\bootstrap-cdn>node make travis

Express server listening on port 3334
GET /bootlint/ 200 557.561 ms - 13162
GET /alpha/ 200 196.069 ms - 15413
GET /bootswatch/ 200 135.637 ms - 52789
GET /data/bootstrapcdn.json 200 1.412 ms - 2399
GET /fontawesome/ 200 122.583 ms - 12911
GET / 200 133.492 ms - 15621
GET /integrations/ 200 113.593 ms - 15516
GET /legacy/ 200 190.055 ms - 120893
GET /showcase/ 200 115.414 ms - 17041

  ........................................................
  ........................................................
  ........................................................
  ........................................................
  ........................!...............................
  ........................................................
  ........................................................
  ........................................................
  ........................................................
  ........................................................
  ........................................................
  ........................................................
  ......................................!.................
  ..........!...........................!.................
  ........................................................
  ........................................................
  ........................................................
  ........................................................
  ........................................................
  ........................................................
  ..........!.............................................
  ..........!!............................................
  ......................................!.................
  ........................................................
  ........................................................
  ........................................................
  ........................................................
  ........................................................
  ........................................................
  ........................................................
  ........................................................
  ........................................................
  ........................................................

  1840 passing (55s)
  8 failing

  1) functional bootstrap https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css has date:
     Uncaught Error: Hostname/IP doesn't match certificate's altnames: "Host: maxcdn.bootstrapcdn.com. is not in the cert's altnames: DNS:*.netdna-ssl.com, DNS:netdna-ssl.com"
      at Object.checkServerIdentity (tls.js:186:15)
      at TLSSocket.<anonymous> (_tls_wrap.js:1023:29)
      at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:582:8)
      at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:424:38)

  2) functional bootstrap https://maxcdn.bootstrapcdn.com/twitter-bootstrap/2.2.1/js/bootstrap.min.js has date:
     Uncaught Error: Hostname/IP doesn't match certificate's altnames: "Host: maxcdn.bootstrapcdn.com. is not in the cert's altnames: DNS:*.netdna-ssl.com, DNS:netdna-ssl.com"
      at Object.checkServerIdentity (tls.js:186:15)
      at TLSSocket.<anonymous> (_tls_wrap.js:1023:29)
      at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:582:8)
      at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:424:38)

  3) functional bootstrap https://maxcdn.bootstrapcdn.com/twitter-bootstrap/2.2.0/js/bootstrap.min.js has date:
     Uncaught Error: Hostname/IP doesn't match certificate's altnames: "Host: maxcdn.bootstrapcdn.com. is not in the cert's altnames: DNS:*.netdna-ssl.com, DNS:netdna-ssl.com"
      at Object.checkServerIdentity (tls.js:186:15)
      at TLSSocket.<anonymous> (_tls_wrap.js:1023:29)
      at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:582:8)
      at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:424:38)

  4) functional bootstrap https://maxcdn.bootstrapcdn.com/twitter-bootstrap/2.1.1/js/bootstrap.min.js has date:
     Uncaught Error: Hostname/IP doesn't match certificate's altnames: "Host: maxcdn.bootstrapcdn.com. is not in the cert's altnames: DNS:*.netdna-ssl.com, DNS:netdna-ssl.com"
      at Object.checkServerIdentity (tls.js:186:15)
      at TLSSocket.<anonymous> (_tls_wrap.js:1023:29)
      at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:582:8)
      at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:424:38)

  5) functional bootlint https://maxcdn.bootstrapcdn.com/bootlint/0.11.0/bootlint.min.js has date:
     Uncaught Error: Hostname/IP doesn't match certificate's altnames: "Host: maxcdn.bootstrapcdn.com. is not in the cert's altnames: DNS:*.netdna-ssl.com, DNS:netdna-ssl.com"
      at Object.checkServerIdentity (tls.js:186:15)
      at TLSSocket.<anonymous> (_tls_wrap.js:1023:29)
      at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:582:8)
      at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:424:38)

  6) functional bootlint https://maxcdn.bootstrapcdn.com/bootlint/0.8.0/bootlint.min.js has date:
     Uncaught Error: Hostname/IP doesn't match certificate's altnames: "Host: maxcdn.bootstrapcdn.com. is not in the cert's altnames: DNS:*.netdna-ssl.com, DNS:netdna-ssl.com"
      at Object.checkServerIdentity (tls.js:186:15)
      at TLSSocket.<anonymous> (_tls_wrap.js:1023:29)
      at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:582:8)
      at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:424:38)

  7) functional bootlint https://maxcdn.bootstrapcdn.com/bootlint/0.8.0/bootlint.min.js has etag:
     Uncaught Error: Hostname/IP doesn't match certificate's altnames: "Host: maxcdn.bootstrapcdn.com. is not in the cert's altnames: DNS:*.netdna-ssl.com, DNS:netdna-ssl.com"
      at Object.checkServerIdentity (tls.js:186:15)
      at TLSSocket.<anonymous> (_tls_wrap.js:1023:29)
      at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:582:8)
      at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:424:38)

  8) functional bootlint https://maxcdn.bootstrapcdn.com/bootlint/0.2.0/bootlint.min.js has date:
     Uncaught Error: Hostname/IP doesn't match certificate's altnames: "Host: maxcdn.bootstrapcdn.com. is not in the cert's altnames: DNS:*.netdna-ssl.com, DNS:netdna-ssl.com"
      at Object.checkServerIdentity (tls.js:186:15)
      at TLSSocket.<anonymous> (_tls_wrap.js:1023:29)
      at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:582:8)
      at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:424:38)



C:\Users\xmr\Desktop\bootstrap-cdn\node_modules\shelljs\src\common.js:340
        throw e;
        ^

Error: exec: internal error
    at Object.error (C:\Users\xmr\Desktop\bootstrap-cdn\node_modules\shelljs\src\common.js:67:11)
    at _exec (C:\Users\xmr\Desktop\bootstrap-cdn\node_modules\shelljs\src\exec.js:266:12)
    at C:\Users\xmr\Desktop\bootstrap-cdn\node_modules\shelljs\src\common.js:275:23
    at assertExec (C:\Users\xmr\Desktop\bootstrap-cdn\make.js:18:50)
    at Function.target.suite (C:\Users\xmr\Desktop\bootstrap-cdn\make.js:36:9)
    at Object.global.target.(anonymous function) [as suite] (C:\Users\xmr\Desktop\bootstrap-cdn\node_modules\shelljs\make.js:36:40)
    at Function.target.travis (C:\Users\xmr\Desktop\bootstrap-cdn\make.js:86:16)
    at Object.global.target.(anonymous function) [as travis] (C:\Users\xmr\Desktop\bootstrap-cdn\node_modules\shelljs\make.js:36:40)
    at C:\Users\xmr\Desktop\bootstrap-cdn\node_modules\shelljs\make.js:48:27
    at Array.forEach (native)

```

**Comment by XhmikosR** [comment]
And the number of failures isn't consistent on each run :/

**Comment by XhmikosR** [comment]
Also, as you can see I still get shelljs' `Error: exec: internal error`.

**Comment by XhmikosR** [comment]
Going back to shelljs 0.5.3 fixes the throw error for me.

**Comment by jmervine** [comment]
You don't get these errors on `^0.5.3`? These look like more MaxCDN errors. ( @jdorfman )

**Comment by XhmikosR** [comment]
I do get the test failures, but I don't get the shell.js internal error with 0.5.3.

**Comment by jmervine** [comment]
I see. Okay, I'll drop the version.

**Comment by jmervine** [comment]
@XhmikosR did dropping the version do anything for you?

**Comment by XhmikosR** [comment]
If you mean the internal error, yeah like I mentioned before. The other
errors must be unrelated.

**Pull request merged**
