### PR TITLE
Add social-related meta tags.

### PR DESCRIPTION
**Pull request by XhmikosR**
This is work in progress, do **not** merge yet.

This is how it will look like: <http://iframely.com/debug?uri=https%3A%2F%2Fbootstrapcdn-dev-pr-811.herokuapp.com%2F>

### CODE REVIEW

**Comment by XhmikosR** [comment]
This is how it will look like  http://iframely.com/debug?uri=https%3A%2F%2Fbootstrapcdn-dev-pr-811.herokuapp.com%2F

**Comment by XhmikosR** [comment]
@jmervine: my only concern about this is if we should use a hardcoded `siteUrl`. I mean, it doesn't make sense to be different let alone I'm not sure if it can hurt SEO, which probably will.

**Comment by jdorfman** [comment]
@XhmikosR it can't hurt SEO.

**Comment by XhmikosR** [comment]
Well it certainly can't help either since both dev and normal site are
being crawled... But if you both agree, we can go with the current patch
and tweak it if needed.

**Comment by jmervine** [comment]
I don't think there's an issue leaving it dynamic for off domains, although not strictly necessary. Were it me, I'd probably leave dynamic, just because it's already that way.

**Pull request merged**
