### PR TITLE
Remove `mangle` from uglifyjs' options.

### PR DESCRIPTION
**Pull request by XhmikosR**
The output should be consistent now.

@jmervine: can you run the lint.sh script in develop and see if you confirm bootlint.min.js is different for you too? That is what led me to this change.

### CODE REVIEW

**Comment by jmervine** [comment]
👍 We'll need to coordinate releasing this to ensure that changes are pushed to s3.

**Comment by XhmikosR** [comment]
@jmervine: feel free to merge this when you are ready to upload the files.

**Comment by jmervine** [comment]
Updated SRI, which is going to make specs fail. Once I push these files, I'll need to release ASAP, as SRI will be broken in production.

**Comment by XhmikosR** [comment]
Why do you have different files?

**Comment by XhmikosR** [comment]
@jmervine: feel free to merge when you are ready.

**Comment by jmervine** [comment]
Yeah, uploading the files and then going to merge and release.

**Pull request merged**
