### PR TITLE
bump dependencies, npm test passed

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by jmervine** [comment]
Looks like tests are failing b/c `html-validator` no longer contains the cli, it's been abstracted here: `html-validator-cli`

**Comment by PeterDaveHello** [comment]
hmmmm ... strange, it passed the test locally, I'll take a look at it.

**Comment by PeterDaveHello** [comment]
hmmmm ... 
```sh
$ rm -rf node_modules/
$ npm install && npm test

.
.
.
.
.

      ✓ -> [object Object]
      ✓ -> [object Object]
      ✓ -> [object Object]
      ✓ -> [object Object]
    contains bootstrap
      ✓ -> 3.3.5
      ✓ -> 3.3.4
      ✓ -> 3.3.2
      ✓ -> 3.3.1
      ✓ -> 3.3.0
      ✓ -> 3.2.0
      ✓ -> 3.1.1
      ✓ -> 3.1.0
      ✓ -> 3.0.3
      ✓ -> 3.0.2
      ✓ -> 3.0.1
      ✓ -> 3.0.0
      ✓ -> 3.0.0-noicons
      ✓ -> 2.3.2
      ✓ -> 2.3.2-noicons
      ✓ -> 2.3.1
      ✓ -> 2.3.0
      ✓ -> 2.2.2
      ✓ -> 2.2.2-noresponsible
      ✓ -> 2.2.1
      ✓ -> 2.2.0
      ✓ -> 2.1.1
      ✓ -> 2.1.0
      ✓ -> 2.0.4


  548 passing (1m)
```

**Comment by PeterDaveHello** [comment]
anyway, I updated the PR to add `html-validator-cli` and see if it pass.

**Comment by jmervine** [comment]
npm test doesn't run the validation that's run on Travis

**Comment by PeterDaveHello** [comment]
Okay, thanks. Now it passed build :+1:

**Comment by jmervine** [comment]
Awesome. I'll merge this later today or early tomorrow, thanks for the contribution!

**Comment by jdorfman** [comment]
Thanks @PeterDaveHello !

**Pull request merged**
