### PR TITLE
Minify bootlint

### LINKED ISSUE #685: bootlint.min.js isn't minified

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #685.

/CC @jmervine

### CODE REVIEW

**Comment by jmervine** [comment]
Uploaded and restarted the tests.

**Comment by XhmikosR** [comment]
@jmervine: doesn't seem to work. I get access denied when I try to open, say https://maxcdn.bootstrapcdn.com/bootlint/0.14.2/bootlint.min.js with my browser.

**Comment by jmervine** [comment]
Bah, missed the perms. Really need to automate this process, but I've been hoping we'd like s3 ( @jdorfman ;-P ), so I've been holding off.

Should be good now.

**Comment by XhmikosR** [comment]
Thanks!

So do the script changes look good to you?

**Comment by jmervine** [comment]
Yeah, it looks fine. 🚢

**Pull request merged**
