### PR TITLE
ignore twitter-bootstrap versions after 2.3.2

### PR DESCRIPTION
**Pull request by jmervine**
addressing https://github.com/MaxCDN/bootstrap-cdn/issues/877

### CODE REVIEW

**Comment by XhmikosR** [comment]
Why don't you use \d? Also I'd skip adding a new dependency. The checks you
do above are fine in my opinion.

**Comment by jdorfman** [comment]
1/3 faster than the previous test

**Comment by jmervine** [comment]
@XhmikosR `\d` didn't work, given that it's just a test and I'm about to run out the door I didn't think it was worth the investigation. Also, assuming you mean `semver` by "new dependancy", it's already installed, just leveraging it.

**Comment by XhmikosR** [comment]
There is no point in requesting any reviews from me any more since Justin
keeps merging stuff without me approving or rejecting.

**Comment by jmervine** [comment]
@XhmikosR I find your reviews valuable, even if I don't take your suggestions. I know Justin was trying to get this out before I took off for the weekend and in conjunction with another PR, hence the rush. That said, even if merged and released, we can always address comments in a new PR.

**Comment by XhmikosR** [comment]
The whole point of PRs, and any kind of code review, is to address issues
before something lands.

I've learned to work like that with anything and any other way just doesn't
make sense to me. It's just more work/time, you name it.

**Pull request merged**
