### PR TITLE
Switch to a Twitter collection instead of a custom solution.

### LINKED ISSUE #761: Switch to a collection for twitter feed
https://dev.twitter.com/web/embedded-timelines/collection

/CC @jdorfman

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #761 

/CC @jdorfman @jmervine

### CODE REVIEW

**Comment by XhmikosR** [comment]
I also, switched to the Twitter API for the buttons while at it.

**Comment by XhmikosR** [comment]
This should be merged after https://github.com/MaxCDN/bootstrap-cdn/pull/763 and after I rebase it.

There should be a performance improvement in this branch.

**Comment by jmervine** [comment]
@jdorfman talked about this at length over the years and the thing is, we really want to be able to moderate which tweets are displayed. 

I love the concept though and have really wanted to do this for quite some time.

**Comment by XhmikosR** [comment]
The only downside is the list of tweets gets too long. Not sure if you can choose another display or something.

**Comment by jdorfman** [comment]
@jmervine I am trying out TweetDeck collections - https://support.twitter.com/articles/20170322

Here is a test. https://twitter.com/getBootstrapCDN/timelines/770731482377621505 

Please don't merge until I approve.

**Comment by jdorfman** [comment]
No way. This is hideous:

image

**Comment by XhmikosR** [comment]
Don't just close it. See if you can configure it first.

**Comment by jdorfman** [comment]
* Dark backgrounds need to go
* The height needs to match what we currently have (4 tweets max)

**Comment by XhmikosR** [comment]
Sure, see if **you** can change it since you can only customize it.

**Comment by jdorfman** [comment]
@XhmikosR I shall see what I can do

**Comment by jdorfman** [comment]
@XhmikosR try:

```html
<a class="twitter-timeline" data-width="260" data-height="800" data-partner="tweetdeck" href="https://twitter.com/getBootstrapCDN/timelines/770731482377621505">Mad Love - Curated tweets by getBootstrapCDN</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
```

**Comment by jdorfman** [comment]
I like your thinking @XhmikosR

**Comment by jdorfman** [comment]
@jmervine the great thing about this is I can edit the feed via Tweetdeck without deploying. Only caveat is that it's not random. I guess I could create multiple timelines and we could randomize those?

**Comment by XhmikosR** [comment]
Done, but please don't merge until I clean the branch.

**Comment by jdorfman** [comment]
@XhmikosR please remove: `<h2>Mad Love</h2>`

**Comment by XhmikosR** [comment]
Will do as soon as in back. I also want to experiment with the dimensions
especially with removing the width so that it inherits the container's
width.

**Comment by jdorfman** [comment]
Yeah and the height should be ~485px

**Comment by jmervine** [comment]
Sweet! Loving this, the Mad Love section is something I wanted to nix for a better solution for quite some time. :D

**Comment by jdorfman** [comment]
Yeah props to @XhmikosR. @jmervine right now I am pruning out old tweets that mention "NetDNA". Got about 20 more or so.

**Comment by jdorfman** [comment]
Remaining tasks:
[] Remove `<h2>Mad Love</h2>`
[] Change `data-height` to `525`

**Comment by XhmikosR** [comment]
@jdorfman: done.

**Comment by jmervine** [comment]
👍 🚢 SO PRETTY! :D

**Pull request merged**
